---
title: "p8105_hw2_yl4362"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```

## Problem 1

**Read and clean the data in Mr. Trash Wheel sheet**
```{r}
mr_trashwheel_df = 
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
    sheet = "Mr. Trash Wheel", 
    range = "A2:N408") %>%
  janitor::clean_names() %>%
  filter(dumpster > 0) %>%
  mutate(sports_balls = as.integer(sports_balls))
```

**Read and clean the data in Precipitation 2017 and 2018 sheets**
```{r}
precipitation_2017_df = 
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2017 Precipitation",
    range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(year = "2017")

precipitation_2018_df = 
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(year = "2018")

precipitation_combined_df =
  rbind(precipitation_2017_df, precipitation_2018_df)

month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precipitation_combined_df = 
  left_join(precipitation_combined_df, month_df, by = "month")
```

